# Generated by Django 5.2 on 2025-06-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("coupon_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="满减门槛"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="开始时间")),
                ("valid_to", models.DateTimeField(verbose_name="截止时间")),
                (
                    "weekdays",
                    models.CharField(
                        blank=True,
                        help_text='如 "6,7" 表示周六周日可用；为空表示任意星期可用',
                        max_length=20,
                        null=True,
                        verbose_name="允许使用的星期几",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="使用说明"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                ("expire_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="使用订单ID"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="coupon.coupon",
                        verbose_name="优惠券模板",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="user.user",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupons",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
