# Generated by Django 5.2 on 2025-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="name",
            field=models.CharField(
                default="未命名优惠券", max_length=100, verbose_name="优惠券名称"
            ),
        ),
    ]
