# Generated by Django 5.2 on 2025-05-01 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DishCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "dish_categories",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("dish_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dish.dishcategory",
                    ),
                ),
            ],
            options={
                "db_table": "dishes",
            },
        ),
    ]
