# Generated by Django 5.2 on 2025-05-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishPriceHistory",
            fields=[
                (
                    "price_record_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="原价"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当前价格"
                    ),
                ),
                ("effective_date", models.DateTimeField(verbose_name="生效时间")),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="dish.dish",
                        verbose_name="关联菜品",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品价格历史",
                "verbose_name_plural": "菜品价格历史",
                "db_table": "dish_price_history",
                "ordering": ["-effective_date"],
            },
        ),
    ]
