# Generated by Django 5.2 on 2025-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminInfo",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("super_admin", "Super Admin"), ("admin", "Admin")],
                        default="admin",
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("last_login_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "admin_infos",
            },
        ),
    ]
