# Generated by Django 5.2 on 2025-06-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("空闲", "green"),
                            ("点菜中", "blue"),
                            ("待餐中", "yellow"),
                            ("待餐较久", "orange"),
                            ("待餐过久", "red"),
                            ("故障中", "black"),
                            ("待支付", "deepblue"),
                        ],
                        default="空闲",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_status",
                        to="order.order",
                    ),
                ),
                (
                    "table",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="table.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "餐桌状态",
                "verbose_name_plural": "餐桌状态表",
            },
        ),
    ]
